name: Build Koda APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          sudo apt update
          # Agregamos TODAS las librerías que el NDK 25 necesita para ejecutarse en 64 bits
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev libncurses6 libncursesw6 \
          libtinfo5 cmake libffi-dev libssl-dev python3-pip python3-setuptools \
          libltdl-dev libgmp-dev libsqlite3-dev openjdk-17-jdk \
          lib32stdc++6 lib32z1 libtinfo5:i386 || true

      - name: Install Buildozer and Cython
        run: |
          pip3 install --user --upgrade "buildozer==1.5.0" "Cython==0.29.33" virtualenv
          export PATH=$PATH:~/.local/bin

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          # Limpieza profunda para que Buildozer no se confunda con versiones viejas
          rm -rf .buildozer
          
          # Forzamos a que Buildozer use su propio entorno descargado
          buildozer -v android debug
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"
          BUILDOZER_ALLOW_ORG_TEST: "1"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Koda-Tactical-App
          path: bin/*.apk
